test(api): add pytest
codycjy/GalaxyEmpireWeb pull request #11
Opened 2024-02-03 12:13 UTC by shallwet

add login,register,and token pytest
add github action on pytest

2024-02-04 03:19 UTC, codycjy requested changes

2024-02-04 03:19 UTC, codycjy commented on .github/workflows/python-check.yaml
change filename to `pytest-api.yaml` or `api-test.yaml`

2024-02-04 03:19 UTC, codycjy commented on master/main.go
Alerady auto migrate at https://github.com/codycjy/GalaxyEmpireWeb/blob/0a2a7530df4405f272d9d4f3155804f7c4af34e9/master/main.go#L47

2024-02-04 03:19 UTC, codycjy commented on master/queue/connections.go
> +		conn, _ := amqp.Dial(connStr)
https://github.com/codycjy/GalaxyEmpireWeb/blob/0a2a7530df4405f272d9d4f3155804f7c4af34e9/master/queue/connections.go#L20-L41
get env in this func!

2024-02-04 03:19 UTC, codycjy commented on master/routes/router.go
> +	balance.Use(middleware.AllowedMiddleware())
balance already use the middleware in user 
duplicate

2024-02-04 03:19 UTC, codycjy commented on master/services/jwtservice/jwtservice.go
> +var jwtKey = []byte("my-secret-key")
建议使用固定的随机字符串

2024-02-04 03:19 UTC, codycjy commented on master/services/userservice/user-service.go
> +	err1 := service.DB.Where("username = ? AND password = ?", username, password).First(&user).Error
This select is enough. Not necessary to check user exist in db

2024-02-04 03:19 UTC, codycjy commented on master/api/auth/login.go
> +type succeedResponse struct {
change struct name maybe `authResponse`

2024-02-04 03:19 UTC, codycjy commented on master/api/auth/login.go
> +		c.JSON(http.StatusBadRequest, api.ErrorResponse{
use 	`http.StatusUnauthorized`

2024-02-04 03:19 UTC, codycjy commented on master/middleware/isuserallowed.go
我没有看懂这个中间件的用途，是为了在用户路径下鉴权？感觉不是很有必要，具体鉴权通过context到service中应该就可以吧（如果我说错了，指正我）
`c.Param("id")` 不能保证存在吧

2024-02-04 03:48 UTC, shallwet commented on master/queue/connections.go
> +		conn, _ := amqp.Dial(connStr)
这个InitConnection本身的的rabbitMQConnection = NewRabbitMQConnection(config.GetRabbitMQConfig())这个参数会读取yaml文件，放在NewRabbitMQConnection里的话应该会报之前的错误

2024-02-04 03:52 UTC, codycjy commented on master/queue/connections.go
> +		conn, _ := amqp.Dial(connStr)
`config.GetRabbitMQConfig()`在这个函数内也判断下环境变量吧 可以避免报错

2024-02-04 04:32 UTC, shallwet commented on master/middleware/isuserallowed.go
确实，当时我测试的是getuser所以有id，现在看来既然已经有了token那说明是这个用户，那我删了这个中间件？，那那个isuserallowed是不是用不上了

2024-02-04 04:35 UTC, shallwet commented on master/middleware/isuserallowed.go
或者我把这个中间件放在getuser这里，a用户token登录自己的账户后，不用通过getuser来获取其他用户的信息

2024-02-04 04:41 UTC, codycjy commented on master/middleware/isuserallowed.go
其他操作一般也用不到getuser这个方法，而且是service层的的调用，不会走到中间件
如果需要可以在getuser里面校验，而不是中间件

2024-02-04 09:40 UTC, codycjy requested changes

2024-02-04 09:40 UTC, codycjy commented on master/api/auth/login.go
> +		c.JSON(http.StatusUnauthorized, api.ErrorResponse{
here should be `StatusBadRequest`

2024-02-04 09:40 UTC, codycjy commented on master/queue/connections.go
> +		connStr = os.Getenv("RABBITMQ_STR")
had better `log.Fatalf` if connStr is empty :)

2024-02-04 09:40 UTC, codycjy commented on master/services/jwtservice/jwtservice.go
不需要每次随机，只需要一个随机 **固定**的字符串 即可 例如`ab9812bef66342192d64257d` 要不然服务重启后无法认证之前的用户
（个人认为通用且较好的方式还是环境变量，可以在代码内内置一个如果获取不到环境变量就用内置的，用于测试等）

2024-02-05 13:30 UTC, codycjy commented on master/queue/connections.go
> +			log.Fatalf("Failed to connect to RabbitMQ: %v", "RABBITMQ_STR is empty")
没必要用 `Fatalf` `Fatal` 就可以了 辛苦修改

2024-02-05 13:31 UTC, codycjy approved these changes

2024-02-05 13:32 UTC, merged